// Common components barrel exports
export { default as TablerIcon } from './TablerIcon.vue'
export { default as FaceDetectionIcon } from './FaceDetectionIcon.vue'
export { default as EmployeeTypeIcon } from './EmployeeTypeIcon.vue'
export { default as StatusIcon } from './StatusIcon.vue'
export { default as LoadingState } from './LoadingState.vue'
export { default as LazyImage } from './LazyImage.vue'
export { default as LoadingSpinner } from './LoadingSpinner.vue'
export { default as DataTable } from './DataTable.vue'
export { default as Modal } from './Modal.vue'
export { default as FormField } from './FormField.vue'
export { default as PullToRefresh } from './PullToRefresh.vue'
export { default as VirtualScroll } from './VirtualScroll.vue'
export { default as SkeletonLoader } from './SkeletonLoader.vue'
export { default as AnimatedNumber } from './AnimatedNumber.vue'
export { default as MobileBottomNav } from './MobileBottomNav.vue'